"""
V2V Task Offloading Simulator — Python Implementation
======================================================
Exact translation of the final HTML/JS simulator (v2v_dataset_simulator.html).

Mobility modes
--------------
  Synthetic   Random-waypoint model (no file needed)
  SUMO FCD    SUMO --fcd-output trace.fcd.xml
  CSV         TAPASCologne / LuST / any generic CSV

Strategies
----------
  V2V_BASELINE   Original delay-greedy heuristic
  LOCAL_ONLY     No offloading (lower bound)
  RANDOM         35 % random offload
  NEAREST        Closest neighbor when queue > 1
  ROUND_ROBIN    Cyclic neighbor assignment when queue > 1

Usage
-----
  python v2v_simulator.py
  python v2v_simulator.py --trace trace.fcd.xml
  python v2v_simulator.py --trace tapas.csv
  python v2v_simulator.py --N 30 --arrival-rate 10 --seed 7
  python v2v_simulator.py --strategies V2V_BASELINE LOCAL_ONLY
"""

from __future__ import annotations

import argparse
import copy
import csv
import math
import os
import xml.etree.ElementTree as ET
from collections import defaultdict
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt


# ═══════════════════════════════════════════════════════════════════════════
# PARAMETERS
# ═══════════════════════════════════════════════════════════════════════════

@dataclass
class SimParams:
    """
    Central configuration dataclass holding all simulation parameters.

    Groups:
      - Synthetic mobility:  number of vehicles (N), map dimensions, speed limits.
      - Simulation time:     total duration (T), step size (dt), RNG seed.
      - Network:             communication range, channel bandwidth, TX power,
                             and noise floor used for Shannon-capacity calculations.
      - Task generation:     Poisson arrival rate, data size range (bytes),
                             CPU cycle demand range, and task deadline range.
      - Vehicle compute:     per-vehicle CPU frequency bounds (GHz, scaled to Hz).
    """
    # Synthetic mobility
    N:            int   = 25
    map_size:     float = 500.0
    max_speed:    float = 20.0

    # Simulation time
    T:            float = 120.0
    dt:           float = 0.5
    seed:         int   = 42

    # Network
    comm_range:   float = 100.0
    bandwidth:    float = 5e6
    tx_power:     float = 0.2
    noise_floor:  float = 1e-13

    # Task generation
    arrival_rate: float = 8.0
    ds_min:       float = 100.0
    ds_max:       float = 1000.0
    cycles_min:   float = 500.0
    cycles_max:   float = 2000.0
    deadline_min: float = 2.0
    deadline_max: float = 6.0

    # Vehicle compute
    cpu_min:      float = 0.5
    cpu_max:      float = 1.5




# ═══════════════════════════════════════════════════════════════════════════
# SEEDED RNG  — Mulberry32 (identical stream to the JS simulator)
# ═══════════════════════════════════════════════════════════════════════════

class Mulberry32:
    """
    Deterministic pseudo-random number generator using the Mulberry32 algorithm.

    Chosen because it produces a bit-identical random stream to the JavaScript
    simulator, enabling reproducible cross-platform comparisons with the same seed.

    Usage:
        rng = Mulberry32(seed=42)
        value  = rng()            # float in [0, 1)
        index  = rng.int_below(n) # integer in [0, n)
    """

    def __init__(self, seed: int) -> None:
        """Initialise the internal 32-bit state from the provided seed."""
        self._s = int(seed) & 0xFFFFFFFF

    def __call__(self) -> float:
        """Advance the state by one step and return a float in [0, 1)."""
        self._s = (self._s + 0x6D2B79F5) & 0xFFFFFFFF
        t = (self._s ^ (self._s >> 15)) & 0xFFFFFFFF
        t = (t * ((1 | self._s) & 0xFFFFFFFF)) & 0xFFFFFFFF
        inner = (((t ^ (t >> 7)) & 0xFFFFFFFF) * ((61 | t) & 0xFFFFFFFF)) & 0xFFFFFFFF
        t = (t ^ (t + inner)) & 0xFFFFFFFF
        return ((t ^ (t >> 14)) & 0xFFFFFFFF) / 4_294_967_296.0

    def int_below(self, n: int) -> int:
        """Return a random integer in the range [0, n)."""
        return int(self() * n)


# ═══════════════════════════════════════════════════════════════════════════
# DATA CLASSES
# ═══════════════════════════════════════════════════════════════════════════

@dataclass
class Task:
    """
    Represents a single computational task generated by a vehicle.

    Lifecycle:
        1. Created by make_task() and placed in the owning vehicle's queue.
        2. Optionally offloaded to a neighbor — assigned_to changes, offloaded=True.
        3. Processed FCFS by _process_fcfs(); start_time and completion_time are set.
        4. Cloned into the global 'done' list once finished or deadline-missed.

    Fields:
        task_id          Unique monotonically increasing identifier.
        origin           trace_id of the vehicle that generated the task.
        assigned_to      trace_id of the vehicle currently responsible for execution.
        data_size        Payload in bytes; determines transmission time.
        cycles           CPU cycles required; combined with vehicle CPU to get exec time.
        deadline         Absolute simulation time by which the task must complete.
        arrival_time     Simulation time when the task was created.
        start_time       Set when processing begins (None if still queued).
        completion_time  Set when execution finishes or deadline expires.
        offloaded        True if the task was transferred to a different vehicle.
        missed_deadline  True if completion_time > deadline.
        locked           Temporary flag preventing double-offloading in one step.
    """
    task_id:         int
    origin:          str
    assigned_to:     str
    data_size:       float
    cycles:          float
    deadline:        float
    arrival_time:    float
    start_time:      Optional[float] = None
    completion_time: Optional[float] = None
    offloaded:       bool = False
    missed_deadline: bool = False
    locked:          bool = False

    def clone(self) -> "Task":
        """Return a shallow copy of this task, used when archiving to the done list."""
        return copy.copy(self)


@dataclass
class Vehicle:
    """
    Represents a single vehicle node in the simulation.

    Fields:
        vid          Integer index used for neighbor-list lookups.
        trace_id     String identifier matching the mobility trace (or str(vid) in synthetic mode).
        x, y         Current 2-D position in metres.
        vx, vy       Velocity components in m/s; used for contact-time prediction.
        cpu          Processing capacity in Hz (cycles per second).
        queue        Ordered list of tasks assigned to this vehicle (FCFS order).
        busy_time    Accumulated wall-clock seconds spent executing tasks; used for CPU utilisation.
        proc_accum   Per-task accumulated processing time (task_id → seconds elapsed),
                     enabling tasks to resume across simulation steps.
    """
    vid:        int
    trace_id:   str
    x:          float    # position x
    y:          float    # position y
    vx:         float    # velocity x component
    vy:         float    # velocity y component
    cpu:        float    # CPU capacity in Hz
    queue:      List[Task] = field(default_factory=list)   # task queue (FCFS)
    busy_time:  float = 0.0
    proc_accum: Dict[int, float] = field(default_factory=dict)


@dataclass
class SnapMetrics:
    """
    Performance snapshot captured every 5 simulation steps.

    Used to build time-series line charts in plot_results().

    Fields:
        time           Simulation time (s) at which the snapshot was taken.
        avg_delay      Mean completion delay (s) over all finished tasks so far.
        completed      Cumulative count of tasks finished within their deadline.
        missed         Cumulative count of tasks that missed their deadline.
        total          Total tasks finished (completed + missed).
        deadline_ratio Fraction of finished tasks that met their deadline [0, 1].
        avg_queue      Mean queue length across all active vehicles.
        cpu_util       Mean CPU utilisation across all vehicles (%).
        comm_energy    Cumulative communication energy consumed (mJ).
        comm_per_task  Communication energy per successfully completed task (mJ).
    """
    time:           float
    avg_delay:      float
    completed:      int
    missed:         int
    total:          int
    deadline_ratio: float
    avg_queue:      float
    cpu_util:       float
    comm_energy:    float
    comm_per_task:  float


@dataclass
class FinalSummary:
    """
    End-of-simulation aggregate metrics for a single strategy run.

    Used to populate bar charts and the summary table in plot_results(),
    and printed to the console by print_summary().

    Fields:
        generated      Total tasks created by the Poisson arrival process (includes
                       any still in queues at simulation end — true workload count).
                       This must be identical across all strategies; if it is not,
                       there is a remaining shared-RNG bug.
        total          Tasks that left the queue (completed + missed); excludes tasks
                       still queued at simulation end — varies by strategy.
        completed      Tasks completed within their deadline.
        missed         Tasks that missed their deadline.
        in_queue       Tasks still in vehicle queues when simulation ended
                       (generated - total); identical across strategies.
        avg_delay      Mean completion delay (s) over successfully finished tasks.
        deadline_sat   Deadline satisfaction rate (%).
        offload_ratio  Percentage of completed tasks that were offloaded.
        comm_energy    Total communication energy consumed (mJ).
        comm_per_task  Communication energy per completed task (mJ) — key metric.
        cpu_util       Average CPU utilisation across all vehicles (%).
    """
    generated:     int
    total:         int
    completed:     int
    missed:        int
    in_queue:      int
    avg_delay:     float
    deadline_sat:  float
    offload_ratio: float
    comm_energy:   float
    comm_per_task: float
    cpu_util:      float


# ═══════════════════════════════════════════════════════════════════════════
# PHYSICS HELPERS
# ═══════════════════════════════════════════════════════════════════════════

def vdist(a: Vehicle, b: Vehicle) -> float:
    """
    Compute the Euclidean distance (metres) between two vehicles.

    Used by build_neighbors() to test communication range, by the offloading
    strategies to find the nearest neighbor, and by channel_rate() to derive SNR.
    """
    return math.sqrt((a.x - b.x) ** 2 + (a.y - b.y) ** 2)


def channel_rate(d: float, bw: float, tx_p: float, noise: float) -> float:
    """
    Estimate the V2V wireless channel capacity (bits/s) using the Shannon formula.

    Args:
        d      Distance between vehicles (m); clamped to 1 m minimum.
        bw     Channel bandwidth (Hz).
        tx_p   Transmit power (W).
        noise  Thermal noise floor (W).

    Returns:
        Shannon capacity in bits per second.
    """
    d = max(d, 1.0)
    snr = tx_p / (noise * (d / 10.0) ** 3.5)
    return bw * math.log2(1.0 + max(snr, 1e-10))


def tx_seconds(data_bytes: float, rate_bps: float) -> float:
    """
    Convert a payload size to transmission time (seconds).

    Args:
        data_bytes  Payload size in bytes.
        rate_bps    Channel rate in bits per second.

    Returns:
        Transmission duration in seconds.
    """
    return data_bytes * 8.0 / rate_bps


def build_neighbors(vehicles: List[Vehicle], comm_range: float) -> List[List[int]]:
    """
    Build an adjacency list representing the V2V communication graph.

    Iterates over all vehicle pairs and adds a bidirectional edge whenever the
    inter-vehicle distance is within comm_range.  The returned list is indexed
    by vehicle position in the vehicles list (i.e., nb[i] contains the indices
    of all vehicles within range of vehicles[i]).

    Args:
        vehicles    List of active Vehicle objects for the current time step.
        comm_range  Maximum communication range in metres.

    Returns:
        nb  — list of neighbor index lists, one per vehicle.
    """
    n = len(vehicles)
    nb: List[List[int]] = [[] for _ in range(n)]
    for i in range(n):
        for j in range(i + 1, n):
            # Add an undirected edge if the pair is within communication range
            if vdist(vehicles[i], vehicles[j]) <= comm_range:
                nb[i].append(j)
                nb[j].append(i)
    return nb


def queue_wait(task: Task, vehicle: Vehicle) -> float:
    """
    Estimate the queuing delay (seconds) a task would experience on a vehicle.

    Sums the remaining execution time of all tasks ahead of the given task in
    the vehicle's FCFS queue (i.e., tasks with smaller task_id that are not yet
    complete).  Used by expected_delay() as the waiting component.

    Args:
        task     The task whose wait time is being calculated.
        vehicle  The vehicle whose queue is being examined.

    Returns:
        Total wait time in seconds before the task can begin execution.
    """
    return sum(
        tk.cycles / vehicle.cpu
        for tk in vehicle.queue
        if tk.task_id < task.task_id and tk.completion_time is None
    )


def expected_delay(task: Task, vehicle: Vehicle, tx: float = 0.0) -> float:
    """
    Estimate the total end-to-end delay (seconds) of executing a task on a vehicle.

    Combines three components:
        tx           Transmission time to reach the target vehicle (0 for local).
        queue_wait   Time spent waiting behind already-queued tasks.
        cycles/cpu   Actual execution time on the vehicle's CPU.

    Used by all offloading strategies to compare local vs. remote execution cost.

    Args:
        task     The task being evaluated.
        vehicle  The candidate vehicle (local or remote neighbor).
        tx       Transmission time in seconds (default 0 for local execution).

    Returns:
        Estimated total delay from now until task completion (seconds).
    """
    return tx + queue_wait(task, vehicle) + task.cycles / vehicle.cpu


# ═══════════════════════════════════════════════════════════════════════════
# TASK GENERATION
# ═══════════════════════════════════════════════════════════════════════════

def poisson_draw(lam: float, rng: Mulberry32) -> int:
    """
    Draw a random integer from a Poisson distribution with mean lambda.

    Uses the Knuth algorithm (multiplicative method): generates uniform samples
    until their product falls below e^(-lambda).  This is numerically equivalent
    to counting events in a unit interval when the average rate is lambda.

    Used each simulation step to determine how many new tasks arrive across the
    vehicle population.

    Args:
        lam  Expected number of arrivals (lambda parameter).
        rng  Seeded Mulberry32 RNG instance.

    Returns:
        Number of task arrivals for this time step.
    """
    L, p, n = math.exp(-lam), 1.0, 0
    while True:
        p *= rng()
        n += 1
        if p <= L:
            break
    return n - 1


def make_task(tid: int, owner: Vehicle, t: float, p: SimParams, rng: Mulberry32) -> Task:
    """
    Instantiate a new Task with randomised parameters drawn from SimParams ranges.

    Data size, CPU cycles, and deadline offset are each sampled uniformly within
    the configured [min, max] bounds.  Data size is converted to bytes (×1e3) and
    cycles to raw cycle count (×1e6) so all arithmetic is in SI units.

    Args:
        tid    Unique task identifier (monotonically increasing counter).
        owner  The vehicle that generated the task (sets origin and initial assignment).
        t      Current simulation time (used as arrival_time and deadline base).
        p      SimParams holding the distribution bounds.
        rng    Seeded RNG for reproducible sampling.

    Returns:
        A fully initialised Task ready to be appended to the owner's queue.
    """
    return Task(
        task_id      = tid,
        origin       = owner.trace_id,
        assigned_to  = owner.trace_id,
        data_size    = (p.ds_min + rng() * (p.ds_max - p.ds_min)) * 1e3,
        cycles       = (p.cycles_min + rng() * (p.cycles_max - p.cycles_min)) * 1e6,
        deadline     = t + p.deadline_min + rng() * (p.deadline_max - p.deadline_min),
        arrival_time = t,
    )


# ═══════════════════════════════════════════════════════════════════════════
# OFFLOADING STRATEGIES
# ═══════════════════════════════════════════════════════════════════════════

# A Move is a (task, source_vehicle_idx, target_vehicle_idx) triple.
Move = Tuple[Task, int, int]


def strategy_v2v_baseline(
    vehicles: List[Vehicle],
    nb:       List[List[int]],
    p:        SimParams,
) -> List[Move]:
    """
    Baseline delay-greedy offloading heuristic.

    For each unstarted task, compares the expected local delay against the
    expected delay at every one-hop neighbor (including transmission time).
    Offloads to the neighbor with the lowest total expected delay, if any
    neighbor beats the local estimate.  No urgency weighting, load penalty,
    link-stability check, or energy term.

    Args:
        vehicles  List of active Vehicle objects.
        nb        Neighbor adjacency list from build_neighbors().
        p         SimParams (uses bandwidth, tx_power, noise_floor).

    Returns:
        List of Move tuples for all tasks selected for offloading.
    """
    moves: List[Move] = []
    for vi, v in enumerate(vehicles):
        pending = [tk for tk in v.queue if tk.start_time is None and not tk.locked]
        if not pending or not nb[vi]:
            continue
        for task in pending:
            best_delay, best_target = expected_delay(task, v), vi
            for ui in nb[vi]:
                u    = vehicles[ui]
                d    = vdist(v, u)
                rate = channel_rate(d, p.bandwidth, p.tx_power, p.noise_floor)
                tx   = tx_seconds(task.data_size, rate)
                delay = expected_delay(task, u, tx)
                if delay < best_delay:
                    best_delay, best_target = delay, ui
            if best_target != vi:
                task.locked = True
                moves.append((task, vi, best_target))
    return moves


def strategy_nearest(vehicles: List[Vehicle], nb: List[List[int]]) -> List[Move]:
    """
    Nearest-neighbor offloading strategy.

    Only activates when a vehicle has more than one unstarted task queued.
    Selects the geographically closest neighbor (by Euclidean distance) and
    offloads the first eligible pending task to it.  Makes no assessment of
    neighbor load, link quality, or task deadlines.

    Args:
        vehicles  List of active Vehicle objects.
        nb        Neighbor adjacency list from build_neighbors().

    Returns:
        List of Move tuples for all selected offloads.
    """
    moves: List[Move] = []
    for vi, v in enumerate(vehicles):
        n_waiting = sum(1 for tk in v.queue if tk.start_time is None)
        if n_waiting <= 1 or not nb[vi]:
            continue
        for task in [tk for tk in v.queue if tk.start_time is None and not tk.locked]:
            ui = min(nb[vi], key=lambda j: vdist(v, vehicles[j]))
            task.locked = True
            moves.append((task, vi, ui))
    return moves


def strategy_random(
    vehicles: List[Vehicle],
    nb:       List[List[int]],
    rng:      Mulberry32,
    prob:     float = 0.35,
) -> List[Move]:
    """
    Random offloading strategy with a fixed probability.

    For each unstarted task on each vehicle, independently tosses a biased coin
    (default 35% probability).  On success, picks a uniformly random neighbor
    as the offload target.  Serves as a stochastic lower-bound reference showing
    the effect of undirected offloading.

    Args:
        vehicles  List of active Vehicle objects.
        nb        Neighbor adjacency list from build_neighbors().
        rng       Seeded Mulberry32 RNG for reproducibility.
        prob      Probability of offloading each individual task (default 0.35).

    Returns:
        List of Move tuples for all randomly selected offloads.
    """
    moves: List[Move] = []
    for vi, v in enumerate(vehicles):
        for task in [tk for tk in v.queue if tk.start_time is None and not tk.locked]:
            if not nb[vi]:
                continue
            if rng() < prob:
                ui = nb[vi][rng.int_below(len(nb[vi]))]
                task.locked = True
                moves.append((task, vi, ui))
    return moves


def strategy_round_robin(
    vehicles: List[Vehicle],
    nb:       List[List[int]],
    rr_state: Dict,
) -> List[Move]:
    """
    Round-robin offloading strategy cycling through available neighbors.

    Only activates when a vehicle has more than one pending task.  Selects a
    neighbor by cycling a global counter (rr_state["idx"]) modulo the number of
    current neighbors, then offloads the first eligible task.  Provides uniform
    load distribution without any quality-of-link awareness.

    Args:
        vehicles  List of active Vehicle objects.
        nb        Neighbor adjacency list from build_neighbors().
        rr_state  Mutable dict with key "idx" holding the current round-robin
                  position; persists across simulation steps.

    Returns:
        List of Move tuples for all selected offloads.
    """
    moves: List[Move] = []
    for vi, v in enumerate(vehicles):
        pending = [tk for tk in v.queue if tk.start_time is None and not tk.locked]
        if len(pending) <= 1 or not nb[vi]:
            continue
        task = pending[0]
        ui   = nb[vi][rr_state["idx"] % len(nb[vi])]
        rr_state["idx"] += 1
        task.locked = True
        moves.append((task, vi, ui))
    return moves


# ═══════════════════════════════════════════════════════════════════════════
# MOBILITY TRACE
# ═══════════════════════════════════════════════════════════════════════════

@dataclass
class Frame:
    """
    A single position record for one vehicle at one timestep in a mobility trace.

    Fields:
        t    Absolute simulation time (seconds).
        x    X coordinate (metres after geo-conversion, or raw metres from SUMO).
        y    Y coordinate (metres).
        spd  Instantaneous speed (m/s); derived from positional diff if missing.
    """
    t:   float
    x:   float
    y:   float
    spd: float


@dataclass
class MobilityTrace:
    """
    Parsed and normalised mobility dataset ready for use by simulate_with_trace().

    Fields:
        vehicle_map  Maps each vehicle ID string to its sorted list of Frames.
        t0           Start timestamp of the trace (seconds); used for time alignment.
        T            Total trace duration in seconds (last_time - t0).
        dt           Median inter-frame interval (seconds); becomes the simulation step.
        map_w        Bounding-box width in metres.
        map_h        Bounding-box height in metres.
        ids          Ordered list of all vehicle ID strings.
        is_geo       True if source coordinates were geographic (lat/lon) and
                     have been projected to metres by _finalise_trace().
    """
    vehicle_map: Dict[str, List[Frame]]
    t0:          float
    T:           float
    dt:          float
    map_w:       float
    map_h:       float
    ids:         List[str]
    is_geo:      bool = False

    @property
    def N(self) -> int:
        """Total number of vehicles in the trace."""
        return len(self.ids)


def _finalise_trace(vehicle_map: Dict[str, List[Frame]]) -> MobilityTrace:
    """
    Validate, sort, and normalise a raw vehicle_map into a MobilityTrace.

    Steps performed:
        1. Sort each vehicle's frame list by ascending time.
        2. Infer the median time step (dt) from the first 20 inter-frame gaps.
        3. Detect geographic coordinates (lat/lon) by checking if x values are
           within [-180, 180] and the span is less than 5 degrees.
        4. If geographic, project to metres using the Equirectangular approximation
           centred on the midpoint latitude.
        5. Back-fill missing speed values using positional differences.
        6. Compute bounding-box dimensions and absolute start time t0.

    Args:
        vehicle_map  Raw dict mapping vehicle ID → list of Frame objects.

    Returns:
        A fully constructed MobilityTrace ready for _interpolate() lookups.

    Raises:
        ValueError  If no vehicles are found or fewer than 2 distinct timesteps exist.
    """
    if not vehicle_map:
        raise ValueError("No vehicles found in trace.")

    ids = list(vehicle_map.keys())
    for vid in ids:
        vehicle_map[vid].sort(key=lambda f: f.t)

    all_times = sorted({f.t for frames in vehicle_map.values() for f in frames})
    if len(all_times) < 2:
        raise ValueError("Trace needs at least 2 distinct timesteps.")

    # Derive median dt from first 20 inter-frame gaps for robustness
    dts = [all_times[i + 1] - all_times[i] for i in range(min(20, len(all_times) - 1))]
    dt  = sorted(dts)[len(dts) // 2]

    all_x = [f.x for frames in vehicle_map.values() for f in frames]
    all_y = [f.y for frames in vehicle_map.values() for f in frames]

    # Detect geographic (lat/lon) coordinates
    is_geo = (abs(all_x[0]) < 180 and abs(all_y[0]) < 90
              and (max(all_x) - min(all_x)) < 5.0)

    if is_geo:
        # Project lat/lon to metres using Equirectangular approximation
        lat_mid       = (min(all_y) + max(all_y)) / 2.0
        m_per_deg_lon = 111_320.0 * math.cos(math.radians(lat_mid))
        m_per_deg_lat = 110_540.0
        x_min, y_min  = min(all_x), min(all_y)
        for frames in vehicle_map.values():
            for f in frames:
                f.x = (f.x - x_min) * m_per_deg_lon
                f.y = (f.y - y_min) * m_per_deg_lat
        all_x = [f.x for frames in vehicle_map.values() for f in frames]
        all_y = [f.y for frames in vehicle_map.values() for f in frames]

    # Back-fill missing speeds using positional differences
    for frames in vehicle_map.values():
        for i, f in enumerate(frames):
            if f.spd == 0.0 and i > 0:
                prev = frames[i - 1]
                d    = math.sqrt((f.x - prev.x) ** 2 + (f.y - prev.y) ** 2)
                f.spd = d / max(f.t - prev.t, 0.01)

    t0 = all_times[0]
    return MobilityTrace(
        vehicle_map = vehicle_map,
        t0  = t0,
        T   = all_times[-1] - t0,
        dt  = dt,
        map_w = max(all_x) - min(all_x) + 1.0,
        map_h = max(all_y) - min(all_y) + 1.0,
        ids = ids,
        is_geo = is_geo,
    )


def parse_sumo_fcd(path: str) -> MobilityTrace:
    """
    Parse a SUMO Floating Car Data (FCD) XML file into a MobilityTrace.

    Expects the standard SUMO FCD format produced by --fcd-output:
        <fcd-export>
          <timestep time="0.0">
            <vehicle id="v0" x="..." y="..." speed="..."/>
            ...
          </timestep>
          ...
        </fcd-export>

    Accepts both 'speed' and 'spd' as the speed attribute name.

    Args:
        path  Filesystem path to the .fcd.xml file.

    Returns:
        A normalised MobilityTrace via _finalise_trace().

    Raises:
        ValueError  If the file contains no <vehicle> elements.
    """
    tree = ET.parse(path)
    root = tree.getroot()
    vehicle_map: Dict[str, List[Frame]] = {}

    for ts in root.findall("timestep"):
        t = float(ts.get("time", 0))
        for v in ts.findall("vehicle"):
            vid = v.get("id", "")
            x   = float(v.get("x", 0))
            y   = float(v.get("y", 0))
            spd = float(v.get("speed") or v.get("spd") or 0)
            if vid not in vehicle_map:
                vehicle_map[vid] = []
            vehicle_map[vid].append(Frame(t=t, x=x, y=y, spd=spd))

    if not vehicle_map:
        raise ValueError("No <vehicle> elements found in FCD file.")
    return _finalise_trace(vehicle_map)


def parse_csv_trace(path: str) -> MobilityTrace:
    """
    Parse a generic CSV mobility trace (TAPASCologne, LuST, or custom) into a MobilityTrace.

    Auto-detects the delimiter (comma vs semicolon) by scanning the first 2 KB.
    Column names are matched case-insensitively against known aliases for ID,
    time, X, Y, and speed.  Speed is optional; if absent, _finalise_trace()
    back-fills it from positional differences.

    Supported column name aliases:
        ID:    id, vehicle_id, vehicleid, node, car, name
        Time:  time, t, timestamp, timestep, step
        X:     x, lon, longitude, pos_x, posx, easting
        Y:     y, lat, latitude, pos_y, posy, northing
        Speed: speed, v, velocity, spd, vel

    Args:
        path  Filesystem path to the CSV file.

    Returns:
        A normalised MobilityTrace via _finalise_trace().

    Raises:
        ValueError  If any required column (ID, time, X, Y) cannot be found.
    """
    ID_COLS   = ["id", "vehicle_id", "vehicleid", "node", "car", "name"]
    TIME_COLS = ["time", "t", "timestamp", "timestep", "step"]
    X_COLS    = ["x", "lon", "longitude", "pos_x", "posx", "easting"]
    Y_COLS    = ["y", "lat", "latitude",  "pos_y", "posy", "northing"]
    SPD_COLS  = ["speed", "v", "velocity", "spd", "vel"]

    def find_col(hl: List[str], names: List[str]) -> int:
        """Return the index of the first matching column name, or -1 if not found."""
        for n in names:
            if n in hl:
                return hl.index(n)
        return -1

    # Detect delimiter from a small sample of the file
    with open(path, newline="", encoding="utf-8-sig") as fh:
        sample = fh.read(2048)
    delim = ";" if sample.count(";") > sample.count(",") else ","

    vehicle_map: Dict[str, List[Frame]] = {}

    with open(path, newline="", encoding="utf-8-sig") as fh:
        reader  = csv.reader(fh, delimiter=delim)
        headers = [h.strip() for h in next(reader)]
        hl      = [h.lower() for h in headers]

        ci_id   = find_col(hl, ID_COLS)
        ci_time = find_col(hl, TIME_COLS)
        ci_x    = find_col(hl, X_COLS)
        ci_y    = find_col(hl, Y_COLS)
        ci_spd  = find_col(hl, SPD_COLS)

        missing = [name for name, idx in
                   [("ID", ci_id), ("time", ci_time), ("X", ci_x), ("Y", ci_y)]
                   if idx < 0]
        if missing:
            raise ValueError(f"Cannot find column(s) {missing}. Headers: {headers}")

        for row in reader:
            if len(row) < 3:
                continue
            try:
                vid = row[ci_id].strip()
                t   = float(row[ci_time])
                x   = float(row[ci_x])
                y   = float(row[ci_y])
                spd = float(row[ci_spd]) if ci_spd >= 0 else 0.0
            except (ValueError, IndexError):
                continue
            if vid not in vehicle_map:
                vehicle_map[vid] = []
            vehicle_map[vid].append(Frame(t=t, x=x, y=y, spd=spd))

    return _finalise_trace(vehicle_map)


def _interpolate(
    frames: List[Frame],
    t_abs:  float,
    dt:     float,
) -> Optional[Tuple[float, float, float, float]]:
    """
    Linearly interpolate a vehicle's position and velocity at an arbitrary time.

    Searches the frame list for the bracketing interval [lo, hi] and interpolates
    x and y.  Velocity components (vx, vy) are derived from the positional
    difference over the interval span, providing a piecewise-linear velocity model.

    Returns None if t_abs falls outside the vehicle's active period (with one dt
    of tolerance at either end), indicating the vehicle is not present at that time.

    Args:
        frames  Sorted list of Frame records for one vehicle.
        t_abs   Absolute simulation time to query.
        dt      Nominal time step, used as an outside-trace tolerance margin.

    Returns:
        (x, y, vx, vy) tuple in metres and m/s, or None if out of range.
    """
    if t_abs < frames[0].t - dt or t_abs > frames[-1].t + dt:
        return None
    lo, hi = frames[0], frames[-1]
    for i in range(len(frames) - 1):
        if frames[i].t <= t_abs <= frames[i + 1].t:
            lo, hi = frames[i], frames[i + 1]
            break
    span = max(hi.t - lo.t, 1e-6)
    frac = min(1.0, max(0.0, (t_abs - lo.t) / span))
    x  = lo.x + (hi.x - lo.x) * frac
    y  = lo.y + (hi.y - lo.y) * frac
    vx = (hi.x - lo.x) / span
    vy = (hi.y - lo.y) / span
    return x, y, vx, vy


# ═══════════════════════════════════════════════════════════════════════════
# SHARED STEP HELPERS
# ═══════════════════════════════════════════════════════════════════════════

def _expire_tasks(vehicles: List[Vehicle], t: float, done: List[Task]) -> None:
    """
    Expire all tasks that have passed their deadline without starting execution.

    For each vehicle, identifies tasks that are still queued (start_time is None)
    but whose deadline has elapsed.  These tasks are marked as missed, given a
    completion_time equal to the current time, cloned into the global done list,
    and removed from the vehicle's queue.

    Called at the start of every simulation step before new arrivals or offloading.

    Args:
        vehicles  List of active Vehicle objects for the current step.
        t         Current simulation time (seconds).
        done      Global list to which expired tasks are appended.
    """
    for v in vehicles:
        expired = [tk for tk in v.queue if tk.start_time is None and tk.deadline < t]
        for tk in expired:
            tk.completion_time = t
            tk.missed_deadline = True
            done.append(tk.clone())
        v.queue = [tk for tk in v.queue
                   if not (tk.start_time is None and tk.deadline < t)]


def _apply_offloads(
    moves:         List[Move],
    vehicles:      List[Vehicle],
    p:             SimParams,
    cum_comm_e:    List[float],
) -> None:
    """
    Execute all offload moves decided by the active strategy.

    For each (task, from_idx, to_idx) triple:
        1. Looks up source and target Vehicle objects by vid.
        2. Removes the task from the source queue, updates its assigned_to field,
           and appends it to the target queue.
        3. Computes the communication energy consumed (mJ) as:
               tx_power × transmission_time × 1000
           and accumulates it in cum_comm_e[0].

    Silently skips any move where the source or target no longer exists (possible
    in trace mode if a vehicle leaves the map mid-step) or where the task has
    already been moved by a previous move in the same step.

    Args:
        moves        List of Move tuples from _dispatch().
        vehicles     List of active Vehicle objects.
        p            SimParams (uses bandwidth, tx_power, noise_floor).
        cum_comm_e   Single-element list acting as a mutable float accumulator.
    """
    v_by_idx = {v.vid: v for v in vehicles}
    for task, from_idx, to_idx in moves:
        fv = v_by_idx.get(from_idx)
        tv = v_by_idx.get(to_idx)
        if fv is None or tv is None or task not in fv.queue:
            continue
        fv.queue.remove(task)
        task.assigned_to = tv.trace_id
        task.offloaded   = True
        task.locked      = False
        tv.queue.append(task)
        d    = vdist(fv, tv)
        rate = channel_rate(d, p.bandwidth, p.tx_power, p.noise_floor)
        cum_comm_e[0] += p.tx_power * tx_seconds(task.data_size, rate) * 1e3


def _process_fcfs(vehicles: List[Vehicle], t: float, dt: float, done: List[Task]) -> None:
    """
    Advance task processing for all vehicles by one simulation step using FCFS scheduling.

    For each vehicle with a non-empty queue:
        1. Sets start_time on the head-of-queue task if not already set.
        2. Increments the accumulated processing time for that task by dt.
        3. Increments the vehicle's busy_time by dt.
        4. If accumulated time ≥ cycles/cpu (task is complete), records
           completion_time = t + dt, flags missed_deadline if late, clones
           the task into done, removes it from the queue, and clears its
           proc_accum entry.

    Only the head of each queue is processed per step, enforcing strict FCFS order.

    Args:
        vehicles  List of active Vehicle objects.
        t         Current simulation time (seconds).
        dt        Simulation time step duration (seconds).
        done      Global list to which completed tasks are appended.
    """
    for v in vehicles:
        if not v.queue:
            continue
        task = v.queue[0]
        if task.start_time is None:
            task.start_time = t
        if task.task_id not in v.proc_accum:
            v.proc_accum[task.task_id] = 0.0
        v.proc_accum[task.task_id] += dt
        v.busy_time += dt
        if v.proc_accum[task.task_id] >= task.cycles / v.cpu:
            task.completion_time = t + dt
            task.missed_deadline = task.completion_time > task.deadline
            done.append(task.clone())
            v.queue.pop(0)
            del v.proc_accum[task.task_id]


def _dispatch(
    strategy:     str,
    vehicles:     List[Vehicle],
    nb:           List[List[int]],
    p:            SimParams,
    t:            float,
    rng_strategy: Mulberry32,
    rr_state:     Dict,
) -> List[Move]:
    """
    Route the current simulation step to the appropriate offloading strategy function.

    Acts as a single dispatch point so both simulation engines (synthetic and
    trace-based) call one function regardless of which strategy is active.
    LOCAL_ONLY returns an empty list, meaning no tasks are ever moved.

    Args:
        strategy      String key identifying the chosen strategy.
        vehicles      List of active Vehicle objects.
        nb            Neighbor adjacency list from build_neighbors().
        p             SimParams passed through to strategy functions.
        t             Current simulation time (seconds).
        rng_strategy  Dedicated RNG instance for strategy randomness only
                      (separate from task-generation RNG, used only by RANDOM).
        rr_state      Round-robin counter dict (used only by ROUND_ROBIN strategy).

    Returns:
        List of Move tuples produced by the selected strategy (empty for LOCAL_ONLY).
    """
    if   strategy == "V2V_BASELINE": return strategy_v2v_baseline(vehicles, nb, p)
    elif strategy == "NEAREST":      return strategy_nearest(vehicles, nb)
    elif strategy == "RANDOM":       return strategy_random(vehicles, nb, rng_strategy)
    elif strategy == "ROUND_ROBIN":  return strategy_round_robin(vehicles, nb, rr_state)
    return []  # LOCAL_ONLY


def _snapshot(
    t:          float,
    vehicles:   List[Vehicle],
    done:       List[Task],
    cum_comm_e: float,
) -> SnapMetrics:
    """
    Compute a SnapMetrics object summarising the current simulation state.

    Calculates all time-series metrics from the global done list and the current
    vehicle list.  Called every 5 steps by both simulation engines to populate
    the snapshots list used for line chart generation.

    Args:
        t           Current simulation time (seconds).
        vehicles    List of active Vehicle objects.
        done        Global list of all finished (or expired) tasks so far.
        cum_comm_e  Cumulative communication energy consumed so far (mJ).

    Returns:
        A SnapMetrics instance with all fields populated for time t.
    """
    fin    = [tk for tk in done if not tk.missed_deadline]
    missed = [tk for tk in done if tk.missed_deadline]
    delays = [tk.completion_time - tk.arrival_time for tk in fin if tk.completion_time]
    avg_d  = sum(delays) / len(delays) if delays else 0.0
    N      = max(len(vehicles), 1)
    avg_q  = sum(len(v.queue) for v in vehicles) / N
    avg_u  = sum(v.busy_time / max(t + 0.001, 0.001) for v in vehicles) / N
    td     = len(done)
    return SnapMetrics(
        time           = round(t, 1),
        avg_delay      = round(avg_d, 4),
        completed      = len(fin),
        missed         = len(missed),
        total          = td,
        deadline_ratio = round(len(fin) / td, 3) if td else 0.0,
        avg_queue      = round(avg_q, 2),
        cpu_util       = round(avg_u * 100.0, 1),
        comm_energy    = round(cum_comm_e, 2),
        comm_per_task  = round(cum_comm_e / len(fin), 3) if fin else 0.0,
    )


def _final_summary(
    done:        List[Task],
    busy_times:  Dict[str, float],
    T:           float,
    cum_comm_e:  float,
    total_veh:   int,
    n_generated: int,
) -> FinalSummary:
    """
    Compute the end-of-simulation FinalSummary from the completed task list.

    Aggregates all per-task data into the scalar metrics reported in the console
    summary table and bar charts.

    Args:
        done         Global list of all tasks that have left the active queue.
        busy_times   Dict mapping each vehicle's trace_id to its total busy_time (s).
        T            Total simulation duration (seconds); used for CPU utilisation.
        cum_comm_e   Total communication energy consumed during the run (mJ).
        total_veh    Total number of vehicles (denominator for CPU utilisation).
        n_generated  Total tasks created by the Poisson process (= tid at end of
                     simulation); must be identical across all strategies.

    Returns:
        A FinalSummary instance with all aggregate metrics populated.
    """
    fin    = [tk for tk in done if not tk.missed_deadline]
    delays = [tk.completion_time - tk.arrival_time for tk in fin if tk.completion_time]
    avg_d  = sum(delays) / len(delays) if delays else 0.0
    offl   = sum(1 for tk in fin if tk.offloaded)
    avg_u  = sum(busy_times.values()) / max(T * max(total_veh, 1), 0.001)
    return FinalSummary(
        generated     = n_generated,
        total         = len(done),
        completed     = len(fin),
        missed        = len(done) - len(fin),
        in_queue      = n_generated - len(done),
        avg_delay     = round(avg_d, 4),
        deadline_sat  = round(len(fin) / len(done) * 100.0, 1) if done else 0.0,
        offload_ratio = round(offl / len(fin) * 100.0, 1) if fin else 0.0,
        comm_energy   = round(cum_comm_e, 2),
        comm_per_task = round(cum_comm_e / len(fin), 3) if fin else 0.0,
        cpu_util      = round(avg_u * 100.0, 1),
    )


# ═══════════════════════════════════════════════════════════════════════════
# SIMULATION ENGINE A — REAL DATASET
# ═══════════════════════════════════════════════════════════════════════════

def simulate_with_trace(
    p:        SimParams,
    strategy: str,
    trace:    MobilityTrace,
) -> Tuple[List[SnapMetrics], FinalSummary]:
    """
    Run a full simulation using real vehicle mobility data from a MobilityTrace.

    Each step reconstructs the active vehicle list by interpolating positions from
    the trace, then runs the full pipeline: task expiry → task generation →
    neighbor graph → offloading → processing.  Vehicle state (queue, busy_time,
    proc_accum) is persisted across steps using per-ID dictionaries, because the
    Vehicle objects themselves are rebuilt each step from trace data.

    Two separate RNG streams are used so that every strategy sees an identical
    task workload regardless of how many RNG calls the offloading logic makes:
        rng_tasks    (seed)     drives CPU assignment, Poisson draws, task params.
        rng_strategy (seed + 1) drives RANDOM strategy offload decisions only.

    The arrival rate is scaled by (active_vehicles / total_ids) each step so
    the overall task load remains proportional to participation density.

    Args:
        p         SimParams controlling all simulation parameters.
        strategy  Strategy name string passed to _dispatch().
        trace     Parsed MobilityTrace from parse_sumo_fcd() or parse_csv_trace().

    Returns:
        (snapshots, summary) — list of per-step SnapMetrics and a FinalSummary.
    """
    rng_tasks    = Mulberry32(p.seed)
    rng_strategy = Mulberry32(p.seed + 1)

    # Assign a fixed random CPU frequency to each vehicle ID at the start
    cpu_map: Dict[str, float] = {
        vid: (p.cpu_min + rng_tasks() * (p.cpu_max - p.cpu_min)) * 1e9
        for vid in trace.ids
    }

    # Persistent state dicts keyed by vehicle trace_id
    v_queues:     Dict[str, List[Task]]       = defaultdict(list)
    v_busy_time:  Dict[str, float]            = defaultdict(float)
    v_proc_accum: Dict[str, Dict[int, float]] = defaultdict(dict)

    done:       List[Task]        = []
    snapshots:  List[SnapMetrics] = []
    tid         = 0
    cum_comm_e  = [0.0]
    rr_state    = {"idx": 0}
    steps       = round(trace.T / trace.dt)
    total_ids   = len(trace.ids)

    for step in range(steps):
        t     = step * trace.dt
        t_abs = t + trace.t0

        # Rebuild the active vehicle list for this step via interpolation
        vehicles: List[Vehicle] = []
        for idx, vid in enumerate(trace.ids):
            pos = _interpolate(trace.vehicle_map[vid], t_abs, trace.dt)
            if pos is None:
                continue
            x, y, vx, vy = pos
            vehicles.append(Vehicle(
                vid=idx, trace_id=vid, x=x, y=y, vx=vx, vy=vy,
                cpu=cpu_map[vid],
                queue=v_queues[vid],
                busy_time=v_busy_time[vid],
                proc_accum=v_proc_accum[vid],
            ))

        N = len(vehicles)
        if N == 0:
            continue

        _expire_tasks(vehicles, t, done)

        # Scale arrival rate by fraction of vehicles currently active in the trace
        lam = p.arrival_rate * trace.dt * (N / max(total_ids, 1))
        for _ in range(poisson_draw(lam, rng_tasks)):
            owner = vehicles[rng_tasks.int_below(N)]
            owner.queue.append(make_task(tid, owner, t, p, rng_tasks))
            tid += 1

        nb    = build_neighbors(vehicles, p.comm_range)
        moves = _dispatch(strategy, vehicles, nb, p, t, rng_strategy, rr_state)
        _apply_offloads(moves, vehicles, p, cum_comm_e)

        # Unlock all tasks before next step
        for v in vehicles:
            for tk in v.queue:
                tk.locked = False

        _process_fcfs(vehicles, t, trace.dt, done)

        # Flush transient Vehicle state back to persistent dicts
        for v in vehicles:
            v_queues[v.trace_id]     = v.queue
            v_busy_time[v.trace_id]  = v.busy_time
            v_proc_accum[v.trace_id] = v.proc_accum

        if step % 5 == 0:
            snapshots.append(_snapshot(t, vehicles, done, cum_comm_e[0]))

    summary = _final_summary(done, dict(v_busy_time), trace.T, cum_comm_e[0], len(trace.ids), tid)
    return snapshots, summary


# ═══════════════════════════════════════════════════════════════════════════
# SIMULATION ENGINE B — SYNTHETIC
# ═══════════════════════════════════════════════════════════════════════════

def simulate_synthetic(
    p:        SimParams,
    strategy: str,
) -> Tuple[List[SnapMetrics], FinalSummary]:
    """
    Run a full simulation using procedurally generated (random-waypoint) mobility.

    Vehicles are initialised with random positions and velocities within the
    configured map_size.  Each step, positions are advanced by vx*dt / vy*dt
    and reflected off map boundaries (elastic bounce), keeping all vehicles
    within the arena throughout the simulation.

    Two separate RNG streams are used so that every strategy sees an identical
    task workload regardless of how many RNG calls the offloading logic makes:
        rng_tasks    (seed)     drives vehicle init, Poisson draws, task params.
        rng_strategy (seed + 1) drives RANDOM strategy offload decisions only.

    The task pipeline per step is identical to simulate_with_trace():
        expiry → generation → neighbors → dispatch → offload → FCFS processing.

    Args:
        p         SimParams controlling all simulation parameters.
        strategy  Strategy name string passed to _dispatch().

    Returns:
        (snapshots, summary) — list of per-step SnapMetrics and a FinalSummary.
    """
    rng_tasks    = Mulberry32(p.seed)
    rng_strategy = Mulberry32(p.seed + 1)

    # Initialise vehicles at random positions with random velocities
    vehicles = [
        Vehicle(
            vid=i, trace_id=str(i),
            x   = rng_tasks() * p.map_size,
            y   = rng_tasks() * p.map_size,
            vx  = (rng_tasks() - 0.5) * p.max_speed * 2.0,
            vy  = (rng_tasks() - 0.5) * p.max_speed * 2.0,
            cpu = (p.cpu_min + rng_tasks() * (p.cpu_max - p.cpu_min)) * 1e9,
        )
        for i in range(p.N)
    ]

    done:      List[Task]        = []
    snapshots: List[SnapMetrics] = []
    tid        = 0
    cum_comm_e = [0.0]
    rr_state   = {"idx": 0}
    steps      = round(p.T / p.dt)

    for step in range(steps):
        t = step * p.dt
        N = len(vehicles)

        # Move all vehicles and apply elastic boundary reflection
        for v in vehicles:
            v.x += v.vx * p.dt
            v.y += v.vy * p.dt
            if v.x <= 0.0 or v.x >= p.map_size:
                v.vx *= -1.0
                v.x = max(0.0, min(p.map_size, v.x))
            if v.y <= 0.0 or v.y >= p.map_size:
                v.vy *= -1.0
                v.y = max(0.0, min(p.map_size, v.y))

        _expire_tasks(vehicles, t, done)

        for _ in range(poisson_draw(p.arrival_rate * p.dt, rng_tasks)):
            owner = vehicles[rng_tasks.int_below(N)]
            owner.queue.append(make_task(tid, owner, t, p, rng_tasks))
            tid += 1

        nb    = build_neighbors(vehicles, p.comm_range)
        moves = _dispatch(strategy, vehicles, nb, p, t, rng_strategy, rr_state)
        _apply_offloads(moves, vehicles, p, cum_comm_e)

        for v in vehicles:
            for tk in v.queue:
                tk.locked = False

        _process_fcfs(vehicles, t, p.dt, done)

        if step % 5 == 0:
            snapshots.append(_snapshot(t, vehicles, done, cum_comm_e[0]))

    busy = {str(v.vid): v.busy_time for v in vehicles}
    summary = _final_summary(done, busy, p.T, cum_comm_e[0], p.N, tid)
    return snapshots, summary


# ═══════════════════════════════════════════════════════════════════════════
# PLOTTING  — mirrors the 5 chart tabs of the HTML simulator
# ═══════════════════════════════════════════════════════════════════════════

COLORS = {
    "V2V_BASELINE": "#2272c3",
    "LOCAL_ONLY":   "#dc2626",
    "RANDOM":       "#d97706",
    "NEAREST":      "#7c3aed",
    "ROUND_ROBIN":  "#ea580c",
}
LABELS = {
    "V2V_BASELINE": "V2V Baseline",
    "LOCAL_ONLY":   "Local Only",
    "RANDOM":       "Random",
    "NEAREST":      "Nearest",
    "ROUND_ROBIN":  "Round Robin",
}


def _ax_style(ax: plt.Axes, title: str, xlabel: str, ylabel: str) -> None:
    """
    Apply consistent visual styling to a matplotlib Axes object.

    Sets the title, axis labels, grid, spine visibility, and tick size to match
    the HTML simulator's chart aesthetic.  Called for every subplot in plot_results().

    Args:
        ax      The Axes object to style.
        title   Chart title string.
        xlabel  X-axis label string.
        ylabel  Y-axis label string.
    """
    ax.set_title(title, fontsize=11, fontweight="bold", pad=8)
    ax.set_xlabel(xlabel, fontsize=10)
    ax.set_ylabel(ylabel, fontsize=10)
    ax.grid(True, linestyle="--", alpha=0.35, linewidth=0.7)
    ax.spines[["top", "right"]].set_visible(False)
    ax.tick_params(labelsize=9)


def plot_results(
    results:    Dict[str, Tuple[List[SnapMetrics], FinalSummary]],
    output_dir: str = "v2v_results",
) -> None:
    """
    Generate and save all performance charts to disk.

    Produces 8 PNG files in output_dir:
        01_avg_delay.png          Line chart — average completion delay over time.
        02_deadline_ratio.png     Line chart — deadline satisfaction ratio over time.
        03_completed.png          Line chart — cumulative completed tasks over time.
        04_comm_energy_per_task.png  Line chart — communication energy per task (key metric).
        05_queue_length.png       Line chart — average queue length over time.
        06_cpu_util.png           Line chart — average CPU utilisation over time.
        07_summary_bars.png       Multi-panel bar chart comparing all final metrics.
        08_summary_table.png      Styled table image of end-of-simulation metrics.

    Each strategy is drawn in its assigned color from the COLORS dict with the
    human-readable label from LABELS.

    Args:
        results     Dict mapping strategy name → (snapshots, summary) tuple,
                    as returned by simulate_synthetic() or simulate_with_trace().
        output_dir  Directory path where PNG files will be written (created if absent).
    """
    os.makedirs(output_dir, exist_ok=True)
    strats = list(results.keys())

    # ── Line charts ───────────────────────────────────────────
    line_charts = [
        ("avg_delay",      "Average Task Completion Delay",     "Avg Delay (s)",       "01_avg_delay.png"),
        ("deadline_ratio", "Deadline Satisfaction Ratio (0–1)", "Ratio",               "02_deadline_ratio.png"),
        ("completed",      "Cumulative Completed Tasks",        "Tasks",               "03_completed.png"),
        ("comm_per_task",  "★ Comm. Energy / Task (mJ) — KEY", "CommE / Task (mJ)",   "04_comm_energy_per_task.png"),
        ("avg_queue",      "Average Queue Length per Vehicle",  "Queue Length (tasks)","05_queue_length.png"),
        ("cpu_util",       "Average CPU Utilisation",           "Utilisation (%)",     "06_cpu_util.png"),
    ]
    for attr, title, ylabel, fname in line_charts:
        fig, ax = plt.subplots(figsize=(9, 4))
        for s in strats:
            snaps, _ = results[s]
            ax.plot([m.time for m in snaps],
                    [getattr(m, attr) for m in snaps],
                    label=LABELS[s], color=COLORS[s], linewidth=2)
        _ax_style(ax, title, "Time (s)", ylabel)
        if attr == "deadline_ratio":
            ax.set_ylim(0, 1.05)
        if attr == "cpu_util":
            ax.set_ylim(0, 105)
        ax.legend(fontsize=9, framealpha=0.9)
        fig.tight_layout()
        fig.savefig(f"{output_dir}/{fname}", dpi=150)
        plt.close(fig)

    # ── Bar charts ────────────────────────────────────────────
    bar_specs = [
        ("avg_delay",     "Avg Delay (s)",            "↓ lower = better"),
        ("deadline_sat",  "Deadline Satisfaction (%)", "↑ higher = better"),
        ("completed",     "Completed Tasks",           "↑ higher = better"),
        ("missed",        "Missed Deadlines",          "↓ lower = better"),
        ("comm_per_task", "CommE / Task (mJ) ★",     ""),
        ("offload_ratio", "Offload Ratio (%)",         ""),
        ("cpu_util",      "CPU Utilisation (%)",       ""),
    ]
    ncols = 3
    nrows = math.ceil(len(bar_specs) / ncols)
    fig, axes = plt.subplots(nrows, ncols, figsize=(ncols * 4.5, nrows * 4))
    for idx, (attr, title, note) in enumerate(bar_specs):
        ax   = axes.flatten()[idx]
        vals = [getattr(results[s][1], attr) for s in strats]
        bars = ax.bar(
            [LABELS[s] for s in strats], vals,
            color=[COLORS[s] for s in strats],
            edgecolor="white", linewidth=0.6, width=0.55,
        )
        top = max(vals) if max(vals) > 0 else 1.0
        for bar, val in zip(bars, vals):
            ax.text(bar.get_x() + bar.get_width() / 2,
                    bar.get_height() + top * 0.015,
                    f"{val:.2f}", ha="center", va="bottom", fontsize=8, fontweight="bold")
        _ax_style(ax, f"{title}\n{note}" if note else title, "", title)
        ax.tick_params(axis="x", labelsize=7, rotation=15)

    for idx in range(len(bar_specs), nrows * ncols):
        axes.flatten()[idx].set_visible(False)

    fig.suptitle("Strategy Comparison — Summary", fontsize=13, fontweight="bold", y=1.01)
    fig.tight_layout()
    fig.savefig(f"{output_dir}/07_summary_bars.png", dpi=150, bbox_inches="tight")
    plt.close(fig)

    # ── Summary table ─────────────────────────────────────────
    cols = ["Strategy", "Generated", "InQueue", "Avg Delay\n(s)", "DL Sat\n(%)",
            "Completed", "Missed", "CommE/Task\n(mJ) ★", "Offload\nRatio (%)", "CPU%"]
    rows = []
    for s in strats:
        sm = results[s][1]
        rows.append([LABELS[s], str(sm.generated), str(sm.in_queue),
                     f"{sm.avg_delay:.3f}", f"{sm.deadline_sat:.1f}",
                     str(sm.completed), str(sm.missed), f"{sm.comm_per_task:.3f}",
                     f"{sm.offload_ratio:.1f}", f"{sm.cpu_util:.1f}"])

    fig, ax = plt.subplots(figsize=(16, max(0.5 * (len(strats) + 2.5), 3)))
    ax.axis("off")
    tbl = ax.table(cellText=rows, colLabels=cols, loc="center", cellLoc="center")
    tbl.auto_set_font_size(False)
    tbl.set_fontsize(9.5)
    tbl.scale(1.0, 1.9)
    for j in range(len(cols)):
        tbl[0, j].set_facecolor("#1F4E79")
        tbl[0, j].set_text_props(color="white", fontweight="bold")
    for i, s in enumerate(strats):
        tbl[i + 1, 0].set_facecolor(COLORS[s] + "30")
        tbl[i + 1, 0].set_text_props(color=COLORS[s], fontweight="bold")
    ax.set_title("Performance Summary\n★ CommE/Task = comm. energy per completed task (mJ)"
                 "  |  Generated & InQueue must match across all strategies",
                 fontsize=11, fontweight="bold", pad=16)
    fig.tight_layout()
    fig.savefig(f"{output_dir}/08_summary_table.png", dpi=150, bbox_inches="tight")
    plt.close(fig)

    print(f"\n  → 8 chart files saved to: {output_dir}/")


# ═══════════════════════════════════════════════════════════════════════════
# CONSOLE SUMMARY
# ═══════════════════════════════════════════════════════════════════════════

def print_summary(results: Dict[str, Tuple[List[SnapMetrics], FinalSummary]]) -> None:
    """
    Print a formatted comparison table of final metrics for all strategies to stdout.

    Columns: strategy name, average delay, deadline satisfaction %, completed tasks,
    missed deadlines, communication energy per task (mJ), and CPU utilisation %.

    Args:
        results  Dict mapping strategy name → (snapshots, summary), as returned
                 by the simulation engines.
    """
    hdr = (f"{'Strategy':<18} {'Generated':>10} {'InQueue':>8} {'Delay(s)':>9} {'DL Sat%':>8} "
           f"{'Done':>6} {'Missed':>7} {'CommE/Task':>11} {'CPU%':>6}")
    sep = "═" * len(hdr)
    print(f"\n{sep}\n{hdr}\n{'─'*len(hdr)}")
    for s, (_, sm) in results.items():
        print(f"{LABELS[s]:<18} {sm.generated:>10} {sm.in_queue:>8} {sm.avg_delay:>9.3f} "
              f"{sm.deadline_sat:>8.1f} {sm.completed:>6} {sm.missed:>7} "
              f"{sm.comm_per_task:>11.3f} {sm.cpu_util:>6.1f}")
    print(sep)
    print("  Generated = tasks created (must match across all strategies)")
    print("  InQueue   = tasks still queued at simulation end (Generated - Done)")
    print("  ★ CommE/Task = comm. energy per completed task (mJ) — KEY metric")
    print("    Comp. energy (~1000 mJ/task) is identical for all strategies and excluded.\n")


# ═══════════════════════════════════════════════════════════════════════════
# CLI
# ═══════════════════════════════════════════════════════════════════════════

ALL_STRATEGIES = [
    "V2V_BASELINE", "LOCAL_ONLY", "RANDOM", "NEAREST", "ROUND_ROBIN"
]


def build_parser() -> argparse.ArgumentParser:
    """
    Construct the command-line argument parser for the simulator.

    Organises arguments into three groups:
        (default)   Trace file path, strategy selection, output directory, plot toggle.
        Simulation  Vehicle count, duration, time step, seed, comm range, map size.
        Tasks       Arrival rate, data size bounds, cycle bounds, deadline bounds,
                    and CPU frequency bounds.

    Returns:
        A configured ArgumentParser ready for parse_args().
    """
    ap = argparse.ArgumentParser(
        description="V2V Task Offloading Simulator",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    ap.add_argument("--trace",       type=str, default=None,
                    help="SUMO FCD .xml or CSV trace (omit for synthetic mode)")
    ap.add_argument("--strategies",  nargs="+",
                    default=["V2V_BASELINE", "LOCAL_ONLY", "RANDOM", "NEAREST", "ROUND_ROBIN"],
                    choices=ALL_STRATEGIES, metavar="S")
    ap.add_argument("--output-dir",  type=str, default="v2v_results")
    ap.add_argument("--no-plots",    action="store_true")

    sim = ap.add_argument_group("Simulation")
    sim.add_argument("--N",            type=int,   default=25)
    sim.add_argument("--T",            type=float, default=120.0)
    sim.add_argument("--dt",           type=float, default=0.5)
    sim.add_argument("--seed",         type=int,   default=42)
    sim.add_argument("--comm-range",   type=float, default=100.0)
    sim.add_argument("--map-size",     type=float, default=500.0)
    sim.add_argument("--max-speed",    type=float, default=20.0)

    tsk = ap.add_argument_group("Tasks")
    tsk.add_argument("--arrival-rate", type=float, default=8.0)
    tsk.add_argument("--ds-min",       type=float, default=100.0)
    tsk.add_argument("--ds-max",       type=float, default=1000.0)
    tsk.add_argument("--cycles-min",   type=float, default=500.0)
    tsk.add_argument("--cycles-max",   type=float, default=2000.0)
    tsk.add_argument("--dl-min",       type=float, default=2.0)
    tsk.add_argument("--dl-max",       type=float, default=6.0)
    tsk.add_argument("--cpu-min",      type=float, default=0.5)
    tsk.add_argument("--cpu-max",      type=float, default=1.5)
    return ap


def main() -> None:
    """
    Entry point for the V2V Task Offloading Simulator.

    Workflow:
        1. Parse CLI arguments and populate a SimParams instance.
        2. If a trace file is provided, detect its format (XML or CSV) and parse it;
           override p.T and p.dt with the trace's actual duration and time step.
        3. Run each requested strategy through the appropriate simulation engine
           (trace-based or synthetic) and collect (snapshots, summary) results.
        4. Print a formatted summary table to stdout.
        5. Generate and save PNG charts unless --no-plots is set.
    """
    args = build_parser().parse_args()

    p = SimParams(
        N=args.N, T=args.T, dt=args.dt, seed=args.seed,
        comm_range=args.comm_range, map_size=args.map_size, max_speed=args.max_speed,
        arrival_rate=args.arrival_rate,
        ds_min=args.ds_min, ds_max=args.ds_max,
        cycles_min=args.cycles_min, cycles_max=args.cycles_max,
        deadline_min=args.dl_min, deadline_max=args.dl_max,
        cpu_min=args.cpu_min, cpu_max=args.cpu_max,
    )

    trace: Optional[MobilityTrace] = None
    if args.trace:
        print(f"\nLoading trace: {args.trace}")
        ext   = os.path.splitext(args.trace)[1].lower()
        trace = parse_sumo_fcd(args.trace) if ext in (".xml", ".fcd") else parse_csv_trace(args.trace)
        geo   = "  [geo→metres]" if trace.is_geo else ""
        print(f"  {trace.N} vehicles  T={trace.T:.1f}s  dt={trace.dt:.2f}s"
              f"  map={trace.map_w:.0f}×{trace.map_h:.0f}m{geo}")
        p.T, p.dt = trace.T, trace.dt
    else:
        print(f"\nSynthetic mode  N={p.N}  T={p.T}s  seed={p.seed}")

    print()
    results: Dict[str, Tuple[List[SnapMetrics], FinalSummary]] = {}
    for s in args.strategies:
        print(f"  [{s:<14}] running…", end="  ", flush=True)
        snaps, sm = (simulate_with_trace(p, s, trace)
                     if trace else simulate_synthetic(p, s))
        results[s] = (snaps, sm)
        print(f"done  completed={sm.completed}  DL_sat={sm.deadline_sat}%"
              f"  CommE/task={sm.comm_per_task:.3f} mJ")

    print_summary(results)

    if not args.no_plots:
        print(f"Generating charts → {args.output_dir}/")
        plot_results(results, output_dir=args.output_dir)


if __name__ == "__main__":
    main()
